steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - '-c'
      - |
        gcloud compute ssh agent-core-dev \
          --zone=asia-southeast1-a \
          --command='git config --global --add safe.directory /home/aliusman/agent-core-dev && cd /home/aliusman/agent-core-dev && GIT_SSH_COMMAND="ssh -i /home/aliusman/.ssh/id_ed25519 -o IdentitiesOnly=yes" git pull && sudo docker compose up -d'
    id: Update dev server
    entrypoint: /bin/bash
    
options:
  logging: CLOUD_LOGGING_ONLY
