version: '3.8'

services:
  agent-core-dev:
    container_name: agent-core-dev
    command: ["pnpm", "start"]
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_KEY_DIRECT=${API_KEY_DIRECT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
      - POSTGRES_URL=${POSTGRES_URL}
      - DAEMON_PROCESS=${DAEMON_PROCESS}
      - SERVER_PORT=${SERVER_PORT}
      - LOAD_CHARACTER_FROM_DB=${LOAD_CHARACTER_FROM_DB}
      - LOAD_CHARACTER_INTERNAL=${LOAD_CHARACTER_INTERNAL}
      - DISABLE_ALL_CLIENTS_INTERACTION=${DISABLE_ALL_CLIENTS_INTERACTION}
      - BUILDIN_TWITTER_USERNAME=${BUILDIN_TWITTER_USERNAME}
      - BUILDIN_TWITTER_COOKIES_AUTH_TOKEN=${BUILDIN_TWITTER_COOKIES_AUTH_TOKEN}
      - BUILDIN_TWITTER_COOKIES_CT0=${BUILDIN_TWITTER_COOKIES_CT0}
      - BUILDIN_TWITTER_COOKIES_GUEST_ID=${BUILDIN_TWITTER_COOKIES_GUEST_ID}
      - BUILDIN_TWITTER_SOCKS_PROXY=${BUILDIN_TWITTER_SOCKS_PROXY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DEEPSEEK_API_URL=${DEEPSEEK_API_URL}
      - SMALL_DEEPSEEK_MODEL=${SMALL_DEEPSEEK_MODEL}
      - MEDIUM_DEEPSEEK_MODEL=${MEDIUM_DEEPSEEK_MODEL}
      - LARGE_DEEPSEEK_MODEL=${LARGE_DEEPSEEK_MODEL}
    ports:
      - "3000:3000"
    restart: always